// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct VideoInfoMessage: Hashable, CustomStringConvertible {
  /// Frame size as delivered (after rotation and scaling).
  var width: Int64
  var height: Int64
  var durationUs: Int64
  var frameRate: Double
  /// Rotation from the file's metadata, already applied to the frames.
  var rotationDegrees: Int64
  var hasAudio: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoInfoMessage? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64
    let durationUs = pigeonVar_list[2] as! Int64
    let frameRate = pigeonVar_list[3] as! Double
    let rotationDegrees = pigeonVar_list[4] as! Int64
    let hasAudio = pigeonVar_list[5] as! Bool

    return VideoInfoMessage(
      width: width,
      height: height,
      durationUs: durationUs,
      frameRate: frameRate,
      rotationDegrees: rotationDegrees,
      hasAudio: hasAudio
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      durationUs,
      frameRate,
      rotationDegrees,
      hasAudio,
    ]
  }
  static func == (lhs: VideoInfoMessage, rhs: VideoInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.durationUs, rhs.durationUs) && MessagesPigeonInternal.deepEquals(lhs.frameRate, rhs.frameRate) && MessagesPigeonInternal.deepEquals(lhs.rotationDegrees, rhs.rotationDegrees) && MessagesPigeonInternal.deepEquals(lhs.hasAudio, rhs.hasAudio)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoInfoMessage")
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: durationUs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: frameRate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotationDegrees, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hasAudio, hasher: &hasher)
  }

  public var description: String {
    return "VideoInfoMessage(width: \(String(describing: width)), height: \(String(describing: height)), durationUs: \(String(describing: durationUs)), frameRate: \(String(describing: frameRate)), rotationDegrees: \(String(describing: rotationDegrees)), hasAudio: \(String(describing: hasAudio)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoFrameMessage: Hashable, CustomStringConvertible {
  var ptsUs: Int64
  var width: Int64
  var height: Int64
  /// Row-major RGBA, `width * height * 4` bytes.
  var rgba: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoFrameMessage? {
    let ptsUs = pigeonVar_list[0] as! Int64
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let rgba = pigeonVar_list[3] as! FlutterStandardTypedData

    return VideoFrameMessage(
      ptsUs: ptsUs,
      width: width,
      height: height,
      rgba: rgba
    )
  }
  func toList() -> [Any?] {
    return [
      ptsUs,
      width,
      height,
      rgba,
    ]
  }
  static func == (lhs: VideoFrameMessage, rhs: VideoFrameMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.ptsUs, rhs.ptsUs) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.rgba, rhs.rgba)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoFrameMessage")
    MessagesPigeonInternal.deepHash(value: ptsUs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rgba, hasher: &hasher)
  }

  public var description: String {
    return "VideoFrameMessage(ptsUs: \(String(describing: ptsUs)), width: \(String(describing: width)), height: \(String(describing: height)), rgba: \(String(describing: rgba)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return VideoInfoMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return VideoFrameMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VideoInfoMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? VideoFrameMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Every call runs on a serial background queue on the platform side, so
/// decoding and encoding never block the platform's main thread. Readers and
/// writers are addressed by ids chosen on the Dart side.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VideoFramesHostApi {
  func openReader(readerId: Int64, path: String, maxDimension: Int64?) throws -> VideoInfoMessage
  /// The next frame in presentation order, or null at the end.
  func nextFrame(readerId: Int64) throws -> VideoFrameMessage?
  /// The frame closest to `timeUs`, for scrubbing. Doesn't move the
  /// sequential position used by [nextFrame].
  func frameAt(readerId: Int64, timeUs: Int64) throws -> VideoFrameMessage
  func closeReader(readerId: Int64) throws
  func openWriter(writerId: Int64, path: String, width: Int64, height: Int64, frameRate: Double, bitRate: Int64?, audioSourcePath: String?) throws
  func addFrame(writerId: Int64, rgba: FlutterStandardTypedData, ptsUs: Int64) throws
  /// Flush, copy the audio track (if any) and close the file.
  func finishWriter(writerId: Int64) throws
  /// Stop and delete the partial file.
  func cancelWriter(writerId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VideoFramesHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VideoFramesHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VideoFramesHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    let openReaderChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.openReader\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.openReader\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      openReaderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let readerIdArg = args[0] as! Int64
        let pathArg = args[1] as! String
        let maxDimensionArg: Int64? = nilOrValue(args[2])
        do {
          let result = try api.openReader(readerId: readerIdArg, path: pathArg, maxDimension: maxDimensionArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openReaderChannel.setMessageHandler(nil)
    }
    /// The next frame in presentation order, or null at the end.
    let nextFrameChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.nextFrame\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.nextFrame\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      nextFrameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let readerIdArg = args[0] as! Int64
        do {
          let result = try api.nextFrame(readerId: readerIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      nextFrameChannel.setMessageHandler(nil)
    }
    /// The frame closest to `timeUs`, for scrubbing. Doesn't move the
    /// sequential position used by [nextFrame].
    let frameAtChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.frameAt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.frameAt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      frameAtChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let readerIdArg = args[0] as! Int64
        let timeUsArg = args[1] as! Int64
        do {
          let result = try api.frameAt(readerId: readerIdArg, timeUs: timeUsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      frameAtChannel.setMessageHandler(nil)
    }
    let closeReaderChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.closeReader\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.closeReader\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      closeReaderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let readerIdArg = args[0] as! Int64
        do {
          try api.closeReader(readerId: readerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeReaderChannel.setMessageHandler(nil)
    }
    let openWriterChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.openWriter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.openWriter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      openWriterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let writerIdArg = args[0] as! Int64
        let pathArg = args[1] as! String
        let widthArg = args[2] as! Int64
        let heightArg = args[3] as! Int64
        let frameRateArg = args[4] as! Double
        let bitRateArg: Int64? = nilOrValue(args[5])
        let audioSourcePathArg: String? = nilOrValue(args[6])
        do {
          try api.openWriter(writerId: writerIdArg, path: pathArg, width: widthArg, height: heightArg, frameRate: frameRateArg, bitRate: bitRateArg, audioSourcePath: audioSourcePathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openWriterChannel.setMessageHandler(nil)
    }
    let addFrameChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.addFrame\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.addFrame\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      addFrameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let writerIdArg = args[0] as! Int64
        let rgbaArg = args[1] as! FlutterStandardTypedData
        let ptsUsArg = args[2] as! Int64
        do {
          try api.addFrame(writerId: writerIdArg, rgba: rgbaArg, ptsUs: ptsUsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addFrameChannel.setMessageHandler(nil)
    }
    /// Flush, copy the audio track (if any) and close the file.
    let finishWriterChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.finishWriter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.finishWriter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      finishWriterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let writerIdArg = args[0] as! Int64
        do {
          try api.finishWriter(writerId: writerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      finishWriterChannel.setMessageHandler(nil)
    }
    /// Stop and delete the partial file.
    let cancelWriterChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.cancelWriter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_frames.VideoFramesHostApi.cancelWriter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      cancelWriterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let writerIdArg = args[0] as! Int64
        do {
          try api.cancelWriter(writerId: writerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelWriterChannel.setMessageHandler(nil)
    }
  }
}
