// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class VideoInfoMessage {
  VideoInfoMessage({
    required this.width,
    required this.height,
    required this.durationUs,
    required this.frameRate,
    required this.rotationDegrees,
    required this.hasAudio,
    required this.audioCompatible,
  });

  /// Frame size as delivered (after rotation and scaling).
  int width;

  int height;

  int durationUs;

  double frameRate;

  /// Rotation from the file's metadata, already applied to the frames.
  int rotationDegrees;

  bool hasAudio;

  /// The audio track can be copied into an MP4 unchanged (false when there
  /// is no audio, or its format doesn't fit the MP4 container).
  bool audioCompatible;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
      durationUs,
      frameRate,
      rotationDegrees,
      hasAudio,
      audioCompatible,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VideoInfoMessage decode(Object result) {
    result as List<Object?>;
    return VideoInfoMessage(
      width: result[0]! as int,
      height: result[1]! as int,
      durationUs: result[2]! as int,
      frameRate: result[3]! as double,
      rotationDegrees: result[4]! as int,
      hasAudio: result[5]! as bool,
      audioCompatible: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoInfoMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(durationUs, other.durationUs) &&
        _deepEquals(frameRate, other.frameRate) &&
        _deepEquals(rotationDegrees, other.rotationDegrees) &&
        _deepEquals(hasAudio, other.hasAudio) &&
        _deepEquals(audioCompatible, other.audioCompatible);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoInfoMessage(width: $width, height: $height, durationUs: $durationUs, frameRate: $frameRate, rotationDegrees: $rotationDegrees, hasAudio: $hasAudio, audioCompatible: $audioCompatible)';
  }
}

class VideoFrameMessage {
  VideoFrameMessage({
    required this.ptsUs,
    required this.width,
    required this.height,
    required this.rgba,
  });

  int ptsUs;

  int width;

  int height;

  /// Row-major RGBA, `width * height * 4` bytes.
  Uint8List rgba;

  List<Object?> _toList() {
    return <Object?>[ptsUs, width, height, rgba];
  }

  Object encode() {
    return _toList();
  }

  static VideoFrameMessage decode(Object result) {
    result as List<Object?>;
    return VideoFrameMessage(
      ptsUs: result[0]! as int,
      width: result[1]! as int,
      height: result[2]! as int,
      rgba: result[3]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoFrameMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ptsUs, other.ptsUs) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(rgba, other.rgba);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoFrameMessage(ptsUs: $ptsUs, width: $width, height: $height, rgba: $rgba)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is VideoInfoMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is VideoFrameMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return VideoInfoMessage.decode(readValue(buffer)!);
      case 130:
        return VideoFrameMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Every call runs on a serial background queue on the platform side, so
/// decoding and encoding never block the platform's main thread. Readers and
/// writers are addressed by ids chosen on the Dart side.
class VideoFramesHostApi {
  /// Constructor for [VideoFramesHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VideoFramesHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
          ? '.$messageChannelSuffix'
          : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<VideoInfoMessage> openReader(int readerId, String path, int? maxDimension) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.video_frames.VideoFramesHostApi.openReader$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      readerId,
      path,
      maxDimension,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VideoInfoMessage;
  }

  /// The next frame in presentation order, or null at the end.
  Future<VideoFrameMessage?> nextFrame(int readerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.video_frames.VideoFramesHostApi.nextFrame$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[readerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as VideoFrameMessage?;
  }

  /// The frame closest to `timeUs`, for scrubbing. Doesn't move the
  /// sequential position used by [nextFrame].
  Future<VideoFrameMessage> frameAt(int readerId, int timeUs) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.video_frames.VideoFramesHostApi.frameAt$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      readerId,
      timeUs,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VideoFrameMessage;
  }

  Future<void> closeReader(int readerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.video_frames.VideoFramesHostApi.closeReader$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[readerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Returns whether the audio of `audioSourcePath` will be copied; audio
  /// that can't go into an MP4 unchanged is dropped instead of failing.
  Future<bool> openWriter(
    int writerId,
    String path,
    int width,
    int height,
    double frameRate,
    int? bitRate,
    String? audioSourcePath,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.video_frames.VideoFramesHostApi.openWriter$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      writerId,
      path,
      width,
      height,
      frameRate,
      bitRate,
      audioSourcePath,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> addFrame(int writerId, Uint8List rgba, int ptsUs) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.video_frames.VideoFramesHostApi.addFrame$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      writerId,
      rgba,
      ptsUs,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Flush, copy the audio track (if any) and close the file.
  Future<void> finishWriter(int writerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.video_frames.VideoFramesHostApi.finishWriter$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[writerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Stop and delete the partial file.
  Future<void> cancelWriter(int writerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.video_frames.VideoFramesHostApi.cancelWriter$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[writerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }
}
