"""Generate packages/bitmapper_core/lib/src/palettes_data.dart from the Python
reference implementation, so the ~500 RGB triples are never hand-typed.

Usage (from the repo root, with the bitmapper venv):

    ../bitmapper/.venv/bin/python tool/gen_palettes.py [path/to/bitmapper]
"""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT.parent / "bitmapper"
sys.path.insert(0, str(REFERENCE))

from bitmapper.palettes import _PALETTES  # noqa: E402

OUT = ROOT / "packages" / "bitmapper_core" / "lib" / "src" / "palettes_data.dart"


def main() -> None:
    lines = [
        "// GENERATED by tool/gen_palettes.py from the Python reference",
        "// (bitmapper/palettes.py). Do not edit by hand; re-run the generator.",
        "",
        "/// Fixed palettes as flat RGB triples, in registration order.",
        "const Map<String, List<int>> kPaletteData = {",
    ]
    for name, colors in _PALETTES.items():
        lines.append(f"  '{name}': [")
        for r, g, b in colors.tolist():
            lines.append(f"    {r}, {g}, {b},")
        lines.append("  ],")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    # Format like the rest of the code (page width from analysis_options).
    subprocess.run(["dart", "format", str(OUT)], check=True, capture_output=True)
    print(f"wrote {OUT} ({len(_PALETTES)} palettes)")


if __name__ == "__main__":
    main()
