// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.allmonty.video_frames

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoInfoMessage (
  /** Frame size as delivered (after rotation and scaling). */
  val width: Long,
  val height: Long,
  val durationUs: Long,
  val frameRate: Double,
  /** Rotation from the file's metadata, already applied to the frames. */
  val rotationDegrees: Long,
  val hasAudio: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoInfoMessage {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      val durationUs = pigeonVar_list[2] as Long
      val frameRate = pigeonVar_list[3] as Double
      val rotationDegrees = pigeonVar_list[4] as Long
      val hasAudio = pigeonVar_list[5] as Boolean
      return VideoInfoMessage(width, height, durationUs, frameRate, rotationDegrees, hasAudio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
      durationUs,
      frameRate,
      rotationDegrees,
      hasAudio,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoInfoMessage
    return MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height) && MessagesPigeonUtils.deepEquals(this.durationUs, other.durationUs) && MessagesPigeonUtils.deepEquals(this.frameRate, other.frameRate) && MessagesPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && MessagesPigeonUtils.deepEquals(this.hasAudio, other.hasAudio)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationUs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.frameRate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasAudio)
    return result
  }
  override fun toString(): String {
    return "VideoInfoMessage(width=$width, height=$height, durationUs=$durationUs, frameRate=$frameRate, rotationDegrees=$rotationDegrees, hasAudio=$hasAudio)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoFrameMessage (
  val ptsUs: Long,
  val width: Long,
  val height: Long,
  /** Row-major RGBA, `width * height * 4` bytes. */
  val rgba: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoFrameMessage {
      val ptsUs = pigeonVar_list[0] as Long
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val rgba = pigeonVar_list[3] as ByteArray
      return VideoFrameMessage(ptsUs, width, height, rgba)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ptsUs,
      width,
      height,
      rgba,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoFrameMessage
    return MessagesPigeonUtils.deepEquals(this.ptsUs, other.ptsUs) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height) && MessagesPigeonUtils.deepEquals(this.rgba, other.rgba)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ptsUs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rgba)
    return result
  }
  override fun toString(): String {
    return "VideoFrameMessage(ptsUs=$ptsUs, width=$width, height=$height, rgba=${rgba.contentToString()})"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoInfoMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoFrameMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VideoInfoMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is VideoFrameMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Every call runs on a serial background queue on the platform side, so
 * decoding and encoding never block the platform's main thread. Readers and
 * writers are addressed by ids chosen on the Dart side.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface VideoFramesHostApi {
  fun openReader(readerId: Long, path: String, maxDimension: Long?): VideoInfoMessage
  /** The next frame in presentation order, or null at the end. */
  fun nextFrame(readerId: Long): VideoFrameMessage?
  /**
   * The frame closest to `timeUs`, for scrubbing. Doesn't move the
   * sequential position used by [nextFrame].
   */
  fun frameAt(readerId: Long, timeUs: Long): VideoFrameMessage
  fun closeReader(readerId: Long)
  fun openWriter(writerId: Long, path: String, width: Long, height: Long, frameRate: Double, bitRate: Long?, audioSourcePath: String?)
  fun addFrame(writerId: Long, rgba: ByteArray, ptsUs: Long)
  /** Flush, copy the audio track (if any) and close the file. */
  fun finishWriter(writerId: Long)
  /** Stop and delete the partial file. */
  fun cancelWriter(writerId: Long)

  companion object {
    /** The codec used by VideoFramesHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `VideoFramesHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VideoFramesHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.video_frames.VideoFramesHostApi.openReader$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val readerIdArg = args[0] as Long
            val pathArg = args[1] as String
            val maxDimensionArg = args[2] as Long?
            val wrapped: List<Any?> = try {
              listOf(api.openReader(readerIdArg, pathArg, maxDimensionArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.video_frames.VideoFramesHostApi.nextFrame$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val readerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.nextFrame(readerIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.video_frames.VideoFramesHostApi.frameAt$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val readerIdArg = args[0] as Long
            val timeUsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.frameAt(readerIdArg, timeUsArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.video_frames.VideoFramesHostApi.closeReader$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val readerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.closeReader(readerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.video_frames.VideoFramesHostApi.openWriter$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val writerIdArg = args[0] as Long
            val pathArg = args[1] as String
            val widthArg = args[2] as Long
            val heightArg = args[3] as Long
            val frameRateArg = args[4] as Double
            val bitRateArg = args[5] as Long?
            val audioSourcePathArg = args[6] as String?
            val wrapped: List<Any?> = try {
              api.openWriter(writerIdArg, pathArg, widthArg, heightArg, frameRateArg, bitRateArg, audioSourcePathArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.video_frames.VideoFramesHostApi.addFrame$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val writerIdArg = args[0] as Long
            val rgbaArg = args[1] as ByteArray
            val ptsUsArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.addFrame(writerIdArg, rgbaArg, ptsUsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.video_frames.VideoFramesHostApi.finishWriter$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val writerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.finishWriter(writerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.video_frames.VideoFramesHostApi.cancelWriter$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val writerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelWriter(writerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
